"""
Prometheus metrics for the agentic chatbot.

Production Features:
- No unbounded labels (session_id, user_id) - prevents OOM
- All labels from bounded enums only
- SLA-aligned buckets
- In-flight request tracking

CARDINALITY RULES:
- NEVER use session_id, user_id, phone_number, or any user-specific value as a label
- All labels MUST come from bounded enums (intent types, product names, status codes)
- If you need per-session tracking, use logs or traces, not metrics
"""

from prometheus_client import Counter, Histogram, Gauge

# =============================================================================
# REQUEST PROCESSING METRICS
# =============================================================================

AGENTIC_MESSAGES_TOTAL = Counter(
    "agentic_messages_total",
    "Total agentic messages processed",
    ["result", "product"],  # result: success/error, product: Travel/Life/etc or "unknown"
)

AGENTIC_LATENCY = Histogram(
    "agentic_latency_seconds",
    "Agentic response latency in seconds",
    ["endpoint"],
    buckets=[0.1, 0.25, 0.5, 1.0, 2.5, 5.0, 10.0, 15.0, 30.0, 60.0],
)

# In-flight request tracking (for concurrency monitoring)
REQUESTS_IN_FLIGHT = Gauge(
    "agentic_requests_in_flight",
    "Number of requests currently being processed",
    ["endpoint"],
)

# =============================================================================
# TOOL EXECUTION METRICS
# =============================================================================

TOOL_CALLS_TOTAL = Counter(
    "agentic_tool_calls_total",
    "Total tool calls by tool name and status",
    ["tool", "status"],  # status: success, error
)

TOOL_LATENCY = Histogram(
    "agentic_tool_latency_seconds",
    "Tool execution latency in seconds",
    ["tool_name", "status"],
    buckets=[0.05, 0.1, 0.25, 0.5, 1.0, 2.5, 5.0, 10.0, 30.0],  # Extended for slow tools
)

TOOL_ERRORS_TOTAL = Counter(
    "agentic_tool_errors_total",
    "Total tool errors by tool name and error category",
    ["tool", "error_category"],  # error_category: validation, service, timeout, unknown
)

TOOL_RETRIES_TOTAL = Counter(
    "agentic_tool_retries_total",
    "Total tool retries by tool name",
    ["tool"],
)

# =============================================================================
# SESSION METRICS
# =============================================================================

SESSION_CACHE_HITS = Counter(
    "agentic_session_cache_hits_total",
    "Session cache hits",
)

SESSION_CACHE_MISSES = Counter(
    "agentic_session_cache_misses_total",
    "Session cache misses",
)

# Active sessions gauge (aggregate count, updated by session manager)
ACTIVE_SESSIONS = Gauge(
    "agentic_active_sessions",
    "Number of currently active sessions",
)

# Redis lock metrics
REDIS_LOCK_TIMEOUTS = Counter(
    "agentic_redis_lock_timeouts_total",
    "Redis lock acquisition timeouts",
    ["scope"],  # scope: session, checkpoint
)

# =============================================================================
# CONVERSATION FLOW METRICS
# =============================================================================

INTENT_CLASSIFICATION_TOTAL = Counter(
    "agentic_intent_classification_total",
    "Intent classification counts",
    ["intent", "product"],  # Bounded enums only
)

RECOMMENDATION_GIVEN_TOTAL = Counter(
    "agentic_recommendation_given_total",
    "Total recommendations given by product",
    ["product"],
)

PURCHASE_LINK_GENERATED_TOTAL = Counter(
    "agentic_purchase_link_generated_total",
    "Total purchase links generated by product",
    ["product"],
)

CONVERSATION_TURNS = Histogram(
    "agentic_conversation_turns",
    "Number of turns in a conversation before completion",
    ["outcome"],  # outcome: completed, abandoned, escalated
    buckets=[1, 2, 3, 5, 10, 15, 20, 30, 50],
)

# Phase counts (aggregate, NOT per-session)
SESSIONS_BY_PHASE = Gauge(
    "agentic_sessions_by_phase",
    "Number of sessions currently in each conversation phase",
    ["phase"],  # phase: info_query, slot_filling, recommendation, service
)

# =============================================================================
# EXTERNAL SERVICE METRICS
# =============================================================================

LIVE_AGENT_HANDOFFS = Counter(
    "agentic_live_agent_handoffs_total",
    "Total live agent handoff requests",
)

WEAVIATE_QUERIES_TOTAL = Counter(
    "agentic_weaviate_queries_total",
    "Total Weaviate queries by status",
    ["status"],  # success, error
)

WEAVIATE_LATENCY = Histogram(
    "agentic_weaviate_latency_seconds",
    "Weaviate query latency in seconds",
    buckets=[0.05, 0.1, 0.25, 0.5, 1.0, 2.5, 5.0, 10.0],
)

LLM_CALLS_TOTAL = Counter(
    "agentic_llm_calls_total",
    "Total LLM calls by model and status",
    ["model", "status"],  # model: gpt-4.1-mini, etc
)

LLM_LATENCY = Histogram(
    "agentic_llm_latency_seconds",
    "LLM call latency in seconds",
    ["model"],
    buckets=[0.1, 0.25, 0.5, 1.0, 2.5, 5.0, 10.0, 15.0, 30.0],
)

# =============================================================================
# WHATSAPP METRICS
# =============================================================================

WA_MESSAGES_PROCESSED_TOTAL = Counter(
    "agentic_wa_messages_processed_total",
    "Total WhatsApp messages processed",
    ["result"],  # result: success, error, duplicate, rate_limited
)

WA_MESSAGE_LATENCY = Histogram(
    "agentic_wa_message_latency_seconds",
    "WhatsApp message processing latency in seconds",
    buckets=[0.5, 1.0, 2.5, 5.0, 10.0, 15.0, 30.0, 60.0],
)

# =============================================================================
# SLOT COLLECTION METRICS
# =============================================================================

SLOTS_COLLECTED = Histogram(
    "agentic_slots_collected",
    "Number of slots collected before recommendation",
    ["product"],
    buckets=[1, 2, 3, 4, 5, 6, 7, 8, 9, 10],
)

# =============================================================================
# MEMORY MANAGEMENT METRICS
# =============================================================================

MEMORY_SUMMARIZATION_TOTAL = Counter(
    "agentic_memory_summarization_total",
    "Total memory summarization operations",
    ["status"],  # success, error
)

MEMORY_SUMMARIZATION_LATENCY = Histogram(
    "agentic_memory_summarization_latency_seconds",
    "Memory summarization latency in seconds",
    buckets=[0.5, 1.0, 2.5, 5.0, 10.0, 30.0],
)

MEMORY_TOKENS_BEFORE_TRIM = Histogram(
    "agentic_memory_tokens_before_trim",
    "Token count in message history before trimming",
    buckets=[500, 1000, 2000, 4000, 8000, 16000, 32000],
)

MEMORY_TOKENS_AFTER_TRIM = Histogram(
    "agentic_memory_tokens_after_trim",
    "Token count in message history after trimming",
    buckets=[250, 500, 1000, 2000, 4000, 8000],
)

MEMORY_MESSAGES_PRUNED = Counter(
    "agentic_memory_messages_pruned_total",
    "Total messages pruned during memory compression",
)

MEMORY_SUMMARY_LENGTH = Histogram(
    "agentic_memory_summary_length_tokens",
    "Length of conversation summaries in tokens",
    buckets=[50, 100, 200, 500, 1000, 2000],
)

# =============================================================================
# MESSAGE HANDLING METRICS
# =============================================================================

MESSAGE_CREATED_TOTAL = Counter(
    "agentic_message_created_total",
    "Total messages created by type",
    ["message_type"],  # human, ai, system, tool
)

MESSAGE_REMOVED_TOTAL = Counter(
    "agentic_message_removed_total",
    "Total messages removed",
    ["removal_type"],  # specific, all
)

MESSAGE_WITH_ID_TOTAL = Counter(
    "agentic_message_with_id_total",
    "Total messages created with proper IDs",
    ["message_type"],
)

MESSAGE_WITH_METADATA_TOTAL = Counter(
    "agentic_message_with_metadata_total",
    "Total messages created with metadata",
    ["message_type"],
)

# LLM Usage Tracking
LLM_INPUT_TOKENS_TOTAL = Counter(
    "agentic_llm_input_tokens_total",
    "Total input tokens used across all LLM calls",
)

LLM_OUTPUT_TOKENS_TOTAL = Counter(
    "agentic_llm_output_tokens_total",
    "Total output tokens generated across all LLM calls",
)

LLM_TOKENS_PER_CALL = Histogram(
    "agentic_llm_tokens_per_call",
    "Token usage per LLM call",
    ["token_type"],  # input, output, total
    buckets=[50, 100, 250, 500, 1000, 2000, 4000, 8000],
)

# Message History Metrics
MESSAGE_HISTORY_SIZE = Histogram(
    "agentic_message_history_size",
    "Number of messages in conversation history",
    buckets=[1, 2, 5, 10, 20, 50, 100, 200],
)

MESSAGE_HISTORY_TOKENS = Histogram(
    "agentic_message_history_tokens",
    "Token count of message history",
    buckets=[500, 1000, 2000, 4000, 8000, 16000, 32000],
)

# =============================================================================
# AUTONOMOUS ROUTING METRICS
# =============================================================================

AUTONOMOUS_ROUTING_TOTAL = Counter(
    "agentic_autonomous_routing_total",
    "Total autonomous routing decisions",
    ["source_node", "target_node"],  # Removed 'reason' to reduce cardinality
)

SELF_CORRECTION_TOTAL = Counter(
    "agentic_self_correction_total",
    "Total self-correction attempts",
    ["trigger", "outcome"],  # trigger: tool_error, low_confidence
)

REFLECTION_LATENCY = Histogram(
    "agentic_reflection_latency_seconds",
    "Latency of reflection/self-correction operations",
    buckets=[0.1, 0.25, 0.5, 1.0, 2.5, 5.0, 10.0],
)

INTERRUPT_REQUESTS_TOTAL = Counter(
    "agentic_interrupt_requests_total",
    "Total interrupt requests for human-in-the-loop",
    ["interrupt_type"],  # live_agent, approval, edit
)

ROUTING_DECISION_LATENCY = Histogram(
    "agentic_routing_decision_latency_seconds",
    "Latency of routing decisions",
    ["source_node"],
    buckets=[0.001, 0.005, 0.01, 0.025, 0.05, 0.1, 0.25],
)

COMMAND_RETURNS_TOTAL = Counter(
    "agentic_command_returns_total",
    "Total Command returns from nodes",
    ["source_node", "has_goto", "has_update"],
)

# =============================================================================
# MULTI-TURN CONVERSATION METRICS
# =============================================================================

PHASE_TRANSITION_TOTAL = Counter(
    "agentic_phase_transition_total",
    "Total conversation phase transitions",
    ["from_phase", "to_phase"],  # Removed 'trigger' to reduce cardinality
)

PHASE_DURATION_TURNS = Histogram(
    "agentic_phase_duration_turns",
    "Number of turns spent in each phase before transition",
    ["phase"],
    buckets=[1, 2, 3, 5, 10, 15, 20, 30],
)

PRONOUN_RESOLUTION_TOTAL = Counter(
    "agentic_pronoun_resolution_total",
    "Total pronoun resolution attempts",
    ["pronoun_type", "resolved"],  # pronoun_type: it, them, there. resolved: true/false
)

REFERENCE_CONTEXT_UPDATES = Counter(
    "agentic_reference_context_updates_total",
    "Total reference context updates",
    ["context_field"],  # last_mentioned_product, last_mentioned_tier
)

INTENT_WITH_SUMMARY_TOTAL = Counter(
    "agentic_intent_with_summary_total",
    "Intent classifications that used summary context",
    ["intent", "had_summary"],  # had_summary: true/false
)
